# name: Deploy to AWS ECS

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Log in to Amazon ECR
#         uses: aws-actions/amazon-ecr-login@v1
      
#       - name: Build and Push to ECR
#         env:
#             aws-access-key-id: secrets.AWS_ACCESS_KEY_ID
#             aws-secret-access-key: secrets.AWS_SECRET_ACCESS_KEY
#             region: ap-south-1
#         run: |
#           # Set variables
#           IMAGE_NAME=medusa-backend
#           AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
#           ECR_REGISTRY=$AWS_ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com
#           ECR_REPO=$ECR_REGISTRY/$IMAGE_NAME

#           # Create ECR repo if not exists
#           aws ecr describe-repositories --repository-names $IMAGE_NAME || \
#           aws ecr create-repository --repository-name $IMAGE_NAME

#           # Build and push Docker image
#           docker build -t $IMAGE_NAME .
#           docker tag $IMAGE_NAME:latest $ECR_REPO:latest
#           docker push $ECR_REPO:latest

#       - name: Deploy to ECS (optional - depends on your setup)
#         run: echo "Add ECS deployment steps here"

name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push to ECR
        run: |
          IMAGE_NAME=medusa-backend
          AWS_REGION=ap-south-1
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_REGISTRY=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
          ECR_REPO=$ECR_REGISTRY/$IMAGE_NAME

          echo "Using ECR repo: $ECR_REPO"

          # Create ECR repo if not exists
          aws ecr describe-repositories --repository-names $IMAGE_NAME || \
          aws ecr create-repository --repository-name $IMAGE_NAME

          # Build and push Docker image
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME:latest $ECR_REPO:latest
          docker push $ECR_REPO:latest
